### ISSUE TITLE
Add Typescript types to DefinitelyTyped

### ISSUE THREAD

**Issue by 75lb** [75lb/byte-size#13]
Add byte-size types to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

Byte-size exports a single function, its input and return types are [documented here](https://github.com/75lb/byte-size/blob/master/index.js#L100). Any questions regarding the types, or if you need me to review the PR please let me know..

**Comment by lntel** [comment]
Is there any type information about the object that the byteSize function returns?

**Comment by 75lb** [comment]
the `byteSize` function is essentially a constructor function, it returns an instance of the class [ByteSize](https://github.com/75lb/byte-size/blob/master/index.js#L55).. the `ByteSize` class has one method `toString()` and three properties `value`, `unit` and `long` - all three of which are strings.

**Comment by lntel** [comment]
Thanks. I've made a PR, just awaiting review by a DT maintainer.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55675

**Comment by 75lb** [comment]
Which editor did you test this in?

**Comment by lntel** [comment]
VSCode 1.60.0

**Comment by 75lb** [comment]
ok thanks.. I'm checking it in Sublime with the MS Typescript plugin.. will check with VSCode too.

**Comment by lntel** [comment]
![image](https://user-images.githubusercontent.com/37447006/132705890-17947f07-400f-4615-b7af-4bbdee5bbdb9.png)

Are you experiencing issues?

**Comment by 75lb** [comment]
only the issues I already mentioned in the PR review.. It didn't work at all until I set the main `byteSize` function as the default export.

**Comment by lntel** [comment]
Ah right, well I've committed those changes to the PR. I apologise, it's my first time working with DT.

**Comment by 75lb** [comment]
That's ok - I don't use Typescript at all so needed to read the docs just to test it.. I'll do another review later on, thanks again for helping with this - the TS users will appreciate it.

**Comment by 75lb** [comment]
byte-size v8.1.0 types [released on DT](https://www.npmjs.com/package/@types/byte-size)
