### ISSUE TITLE
The unit ‘kB’ should be ’KB‘ ?

### ISSUE THREAD

**Issue by realyuyanan** [75lb/byte-size#14]
![image](https://user-images.githubusercontent.com/22365107/181161288-6ddaba07-418b-4e27-90b9-4873ce90f516.png)

**Comment by 75lb** [comment]
Hi, no I believe `kB` is correct. [Link](https://en.wikipedia.org/wiki/Kilobyte).

<img width="1079" alt="Screenshot 2022-07-31 at 10 52 39" src="https://user-images.githubusercontent.com/1247980/182020867-7f2d6677-c6bc-405b-910f-2d127426d384.png">
