### ISSUE TITLE
Support IEC & Metric

### ISSUE THREAD

**Issue by dodekeract** [75lb/byte-size#2]
It would be nice if you could use the proper units or at least give an option to use them.
On the right side of [this link](https://en.wikipedia.org/wiki/Gigabyte) is a table which should explain what I mean. Also I think you should include Petabytes too, because they might be relevant already. An example would be the total written bytes on a 4TB harddrive. That could come close to a petabyte for some use-cases.

If you have no time or will to change this module tell me and I will probably submit a pull request in some weeks.

**Comment by 75lb** [comment]
i'll look into it, thanks for the report

**Comment by 75lb** [comment]
fixed and released in v2.0.0, cheers
