### ISSUE TITLE
Convert string into number

### ISSUE THREAD

**Issue by simon-p-r** [75lb/byte-size#3]
Would you be willing to export a function that takes the current string output format and convert it into a number? Basically the opposite of the current function.

Thanks

**Comment by 75lb** [comment]
hmm, probably not - i'd say that warranted a separate module (which i have no plans to write atm)

**Comment by simon-p-r** [comment]
Fair enough I will write a module if I can't find one!  Thanks for the swift response!

**Comment by dodekeract** [comment]
@simon-p-r in case you don't want to do it, I'd implement it too. Just tell me who of us shall write it. :)

**Comment by simon-p-r** [comment]
Hi @dodekeract I have limited experience as have never had to convert data sizes before, if you require something quickly it maybe be best for you to start something.  I could always add tests and readme for a repo to help out!

**Comment by dodekeract** [comment]
@simon-p-r https://github.com/dodekeract/reverse-byte-size Hope this suits your needs.

Just open an issue if you notice anything weird/unintended or something.

**Comment by dodekeract** [comment]
@75lb I'd appreciate (if you think that's okay) if you'd link to reverse-byte-size from your README. It's up to you, but I think it's useful to know that there is a module that converts your formats back to the initial data.

**Comment by 75lb** [comment]
yeah, i'm fine with that.. although i think your project would benefit from some tests and CI first..
