### ISSUE TITLE
No Typescript types

### ISSUE THREAD

**Issue by Kapsonfire-DE** [75lb/byte-size#8]
Could you add this?

**Comment by 75lb** [comment]
Sorry, this is a native, isomorphic javascript library.. for Typescript, see [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

**Comment by shah-id** [comment]
Even though it is javascript library, typescript types can be provided in the library itself.

**Comment by 75lb** [comment]
@shah-id yes, Typescript types could be included.. we could include Flow types too.. Coffeescript.. there are many different third party abstractions and interfaces we could include... 

I write and maintain Javascript and Javascript only - sorry.. Typescript has its own ecosystem and  [package repository](https://github.com/DefinitelyTyped/DefinitelyTyped)..

**Comment by zdila** [comment]
We switched to https://github.com/sindresorhus/pretty-bytes which provides the TS types out of the box.

**Comment by 75lb** [comment]
I've [raised a ticket](https://github.com/75lb/byte-size/issues/13) to add types, hopefully someone with Typescript experience will pick this up soon.

**Comment by 75lb** [comment]
byte-size v8.1.0 types [released on DT](https://www.npmjs.com/package/@types/byte-size)

**Comment by Kapsonfire-DE** [comment]
Thanks for raising this!
